use sample;
ALTER TABLE site_pro ADD CONSTRAINT site_pro_ibfk_1 FOREIGN KEY (siteId) REFERENCES site (siteId) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE site_pro ADD CONSTRAINT site_pro_ibfk_2 FOREIGN KEY (processId) REFERENCES process (processId) ON UPDATE CASCADE ON DELETE CASCADE;